### ISSUE TITLE
why choose jekyll instead of hexo?

### ISSUE THREAD

**Issue by thinkycx** [zry656565/heaven-blog#7]
Nowadays, hexo seems to be better than jekyll.

**Comment by zry656565** [comment]
Sorry for late reply, this project is quite unmaintained for a long time. I will post some new articles on it, so I won't consider about migrating it to hexo.

**Comment by thinkycx** [comment]
> Sorry for late reply, this project is quite unmaintained for a long time. I will post some new articles on it, so I won't consider about migrating it to hexo.

I have changed mysite to jekyll. Awesome jekyll!

**Comment by zry656565** [comment]
@thinkycx hoho, sounds cool. enjoy. 🍻
