### ISSUE TITLE
rxjs-practice-01这篇文章的Demo在IE中的问题

### ISSUE THREAD

**Issue by Tindtily** [zry656565/heaven-blog#8]
我把三个例子在IE11和Edge中做了测试，效果很差。不知道问题的原因出在哪里。在Chrome里面效果还是很棒的。

**Comment by zry656565** [comment]
抱歉这么晚才回复，可能在 IE11 和 Edge 的渲染引擎中，transform 的处理方式不太一致。具体原因我也不太清楚，可以考虑使用 `position: absolute;` 绝对定位来实现。
